json.outstandingReceivables @outstanding_receivables
json.outstandingPayables @outstanding_payables
json.settledReceivables @settled_receivables
json.settledPayables @settled_payables
json.balanceByFriends @balance_by_friends
json.billsByFriend @bills_by_friend
json.outstandingBalances @outstanding_balances
